config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"

  root to: "main#index"

  get "dashboard", to: "main#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cards
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def index
   
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = current_user.cards
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to card_url(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
        puts "SHIT SHIT SHIT"
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:name, :elements, :user_id)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user!, except[:send_new_password]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/about/index.html.erb
<body class="bg-black">

    <div class="title">
        <h1 class="w-screen flex justify-center items-center text-7xl text-white h-[37rem]"> Creating inovation For Everyday people</h1>
    </div>

    <div class="card-container flex items-center justify-center">
        <div class="card relative top-1/2 left-1/2 flex float-left w-96 h-64 p-12">
            <div class="image w-full h-full overflow-hidden">
            <%= image_tag('eduimg.jpg') %>
            </div>
            <div class="details absolute top-0 left-0 h-full bg-blue-700">
            <div class="center p-5 text-center bg-white absolute top-1/2">
                <h1 class="m-0 p-0 text-red-600 leading-5 text-xl uppercase">Education</h1>
                <p class="my-3 p-0 text-gray-800">Graudated from Augusta Technical College with a Associates in Cyber Security.</p>
            </div>
            </div>
        </div>

        <div class="card relative top-1/2 left-1/2 flex float-left w-96 h-64 p-12">
            <div class="image w-full h-full overflow-hidden">
            <%= image_tag('me.jpg') %>
            </div>
            <div class="details absolute top-0 left-0 h-full bg-blue-700">
            <div class="center p-5 text-center bg-white absolute top-1/2">
                <h1 class="m-0 p-0 text-red-600 leading-5 text-xl uppercase">Projects</h1>
                <p class="my-3 p-0 text-gray-800">Graudated from Augusta Technical College with a Associates in Cyber Security</p>
            </div>
            </div>
        </div>

        <div class="card relative top-1/2 left-1/2 flex float-left w-96 h-64 p-12">
            <div class="image w-full h-full overflow-hidden">
            <%= image_tag('eduimg.jpg') %>
            </div>
            <div class="details absolute top-0 left-0 h-full bg-blue-700">
            <div class="center p-5 text-center bg-white absolute top-1/2">
                <h1 class="m-0 p-0 text-red-600 leading-5 text-xl uppercase">Education</h1>
                <p class="my-3 p-0 text-gray-800">Graudated from Augusta Technical College with a Associates in Cyber Security</p>
            </div>
            </div>
        </div>
    </div>
    
</body>

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= card.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Elements:</strong>
    <%= card.elements %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this card", card, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this card', edit_card_path(card), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, class: "contents") do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <% if card.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :elements %>
    <%= form.number_field :elements, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing card</h1>

  <%= render "form", card: @card %>

  <%= link_to "Show this card", @card, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cards", cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cards</h1>
    <%= link_to 'New card', new_card_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="cards" class="min-w-full">
    <%= render @cards %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New card</h1>

  <%= render "form", card: @card %>

  <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cards/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @card %>


    <%= link_to 'Edit data', edit_card_path(@card), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
    <%= link_to 'Edit this card', edit_card_path(@card), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this card', card_path(@card), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to cards', cards_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioWebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "style.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <main>
    <%= render partial: "shared/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<div class="inline-flex justify-center">
    <img src="../assets/abacus.jpg">
    <div class="bg-gray-700 bg-gradient-to-br from-black border-1 p-4 border-black rounded-lg absolute shadow-lg w-5/12 max-w-3xl min-w-3xl lg:mt-72 lg:h-80 md:h-80 md:mt-30">
        <h2 class="justify-center text-center align-text shadow-lg mb-4 mt-2 text-3xl text-white">KPI Scorecard Generator.</h2> 
        <div class="flex space-x-2">
            <div class="order-1 w-6/12 h-full max-w-sm shadow-lg rounded-lg">
                <img src="../assets/abacus.jpg" class="rounded-lg">
            </div>
            <div class="order-2">
                <h3 class="justify-center text-center align-text text-xs text-white shadow-lg mb-2"> • Faster then excel for your requirements.</h3>
                <h3 class="justify-center text-center align-text text-xs text-white shadow-lg mb-2"> • More specific then excel for your needs.</h3>   
            </div>
        </div> 
    </div>
</div>      

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <div> <%= message %></div>
        <% end %>
    </div>
 <% end %>

app/views/shared/_navbar.html.erb
<nav class="py-2.5 bg-black">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

    <%= link_to "Dylan", root_path, :style => 'color: white' %>

    <button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
      <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li class="nav-item">
          <a href="/about" class="block py-2 pr-4 pl-3 text-gray-400 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent "><% if user_signed_in? %><%= current_user.email%><% end %></a>
        </li>
        <li>
          <%= button_to 'Log in', new_user_session_path, method: :get %>
        </li>
        <li>
          <%= button_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= button_to 'Create Card', new_card_path, method: :get %>
        </li>
      </ul>
    </div>
  </div>
</nav>